[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
meridian = "2rnq72LPCH1aAGKvJrFU6YWAy6XCQh2ERofPhuqA7YCG"

[programs.devnet]
meridian = "2rnq72LPCH1aAGKvJrFU6YWAy6XCQh2ERofPhuqA7YCG"

[provider]
cluster = "devnet"
wallet = "keys/admin.json"
